# create:
# conda env create --file conda_env.yml
name: lflows_iclr24

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.9
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - matplotlib
  - numpy #=1.23
  - scipy #=1.10 #.0
  - scikit-learn
  - pytest
  - pyyaml
  - tensorboard
  - tqdm
  - scikit-image
  - seaborn #=0.12.2
  - plotly
  - optuna
  - lightning
  - geopandas
  - pillow
  - cartopy
  - pyarrow
#  - cartopy_offlinedata
  - pip
  - pip:
      - torchtestcase
      - ./nflows_extended
      - -e .  # install package in development mode
      - umnn
      - parameterized
      - siren-pytorch
      - torchquad
      - torchdiffeq==0.2.3
      - iteround
